# Generated by Django 4.2.5 on 2023-10-04 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_is_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_new',
            new_name='is_last',
        ),
    ]
